### ISSUE TITLE
Error while creating a tool `Cannot read properties of undefined (reading 'status')`

### ISSUE THREAD

**Issue by ItzCrazyKns** [homanp/superagent-js#12]
Creating an Tool using the Superagent client returns the following error `Cannot read properties of undefined (reading 'status')`.

# Steps to reproduce

1. Create a Superagent client using superagent-js
2. Create a tool using the Superagent client

```ts
import { SuperAgentClient } from "superagentai-js"

const client = new SuperAgentClient({
    environment: "https://api.beta.superagent.sh",
    token: process.env.SUPERAGENT_API_TOKEN
})

const {data: tool} = await client.tool.create({
    name: "Browser",
    description: "A portal to the internet, useful for answering questions about websites or urls.",
    type: "BROWSER",
})
```

**Comment by elisalimli** [comment]
I just replicated this and it works fine for me. 

can you share your superagentai-js version?

**Comment by ItzCrazyKns** [comment]
Its `0.1.48`

**Comment by elisalimli** [comment]
mine is same, please check your api token again.

**Comment by ItzCrazyKns** [comment]
Just checked it, it creates the agent but throws error and doesn't moves ahead in the code

**Comment by homanp** [comment]
@ItzCrazyKns `returnDirect` is required I will update docs

**Comment by ItzCrazyKns** [comment]
Will be fixed by https://github.com/homanp/superagent/pull/613
